import React, { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowDownUp, ArrowUpRight, Bell, CalendarDays, Check, CheckCheck, ChevronDown, CircleHelp, CirclePlus, ClipboardList, FolderKanban, LayoutDashboard, ListTodo, LogOut, Menu, MoreHorizontal, Search, Settings2, Sparkles, Target, Trash2, TrendingUp, X } from 'lucide-react';
import { downloadAttachment, request } from './api';

const labels = { NOT_STARTED: 'Not started', IN_PROGRESS: 'In progress', COMPLETED: 'Completed', PENDING: 'Pending', LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High' };
const initials = (name='') => name.split(/\s+/).slice(0,2).map(p=>p[0]).join('').toUpperCase();
const prettyDate = (value) => value ? new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric'}) : 'No date';
function App(){
  const [token,setToken]=useState(localStorage.getItem('taskflow_token')||'');
  const [user,setUser]=useState(null); const [tab,setTab]=useState('Overview'); const [projects,setProjects]=useState([]); const [tasks,setTasks]=useState([]); const [dashboard,setDashboard]=useState(null);
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [projectStatus,setProjectStatus]=useState(''); const [taskStatus,setTaskStatus]=useState(''); const [priority,setPriority]=useState('');
  const [modal,setModal]=useState(''); const [editing,setEditing]=useState(null); const [form,setForm]=useState({}); const [mobileNav,setMobileNav]=useState(false); const [toast,setToast]=useState('');
  const notify=(message)=>{setToast(message);setTimeout(()=>setToast(''),2600)};
  const signOut=useCallback(()=>{localStorage.removeItem('taskflow_token');setToken('');setUser(null);setProjects([]);setTasks([]);setDashboard(null);},[]);
  const load=useCallback(async()=>{if(!token)return;setLoading(true);setError('');try{const [me,p,t,d]=await Promise.all([request('/auth/me',{token}),request(`/projects?search=${encodeURIComponent(tab==='Projects'?search:'')}&status=${projectStatus}`,{token}),request(`/tasks?search=${encodeURIComponent(tab==='Tasks'?search:'')}&status=${taskStatus}&priority=${priority}&limit=100`,{token}),request('/dashboard',{token})]);setUser(me.user);setProjects(p.items);setTasks(t.items);setDashboard(d);}catch(e){if(e.status===401){signOut();setError('Your session expired. Please sign in again.');}else setError(e.message);}finally{setLoading(false);}},[token,tab,search,projectStatus,taskStatus,priority,signOut]);
  useEffect(()=>{if(token)load();},[token,load]);
  async function submitAuth(e){e.preventDefault();setError('');try{const body=await request(`/auth/${form.mode||'login'}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('taskflow_token',body.token);setToken(body.token);setUser(body.user);}catch(e){setError(e.message);}}
  async function saveEntity(e){e.preventDefault();setError('');try{if(modal==='project'){await request(editing?`/projects/${editing.id}`:'/projects',{method:editing?'PUT':'POST',token,body:JSON.stringify({...form,startDate:form.startDate?new Date(form.startDate).toISOString():null,endDate:form.endDate?new Date(form.endDate).toISOString():null})});}else{await request(editing?`/tasks/${editing.id}`:'/tasks',{method:editing?'PUT':'POST',token,body:JSON.stringify({...form,dueDate:form.dueDate?new Date(form.dueDate).toISOString():null})});}setModal('');setEditing(null);setForm({});notify(editing?'Changes saved':'Created successfully');await load();}catch(e){setError(e.message);}}
  async function remove(item,type){if(!window.confirm(`Delete “${item.name}”? This cannot be undone.`))return;try{await request(`/${type}/${item.id}`,{method:'DELETE',token});notify(`${type==='projects'?'Project':'Task'} deleted`);await load();}catch(e){setError(e.message);}}
  function openForm(type,item=null){setError('');setEditing(item);setForm(item?{...item,startDate:item.startDate?.slice(0,10)||'',endDate:item.endDate?.slice(0,10)||'',dueDate:item.dueDate?.slice(0,10)||''}:{status:type==='project'?'NOT_STARTED':type==='task'?'PENDING':undefined,priority:'MEDIUM',projectId:projects[0]?.id||''});setModal(type);}
  async function toggleTask(task){try{await request(`/tasks/${task.id}`,{method:'PUT',token,body:JSON.stringify({status:task.status==='COMPLETED'?'PENDING':'COMPLETED'})});await load();notify(task.status==='COMPLETED'?'Task reopened':'Task completed');}catch(e){setError(e.message);}}
  async function attachFile(taskId,file){const body=new FormData();body.append('file',file);try{await request(`/tasks/${taskId}/attachments`,{method:'POST',token,body});notify('File attached');await load();}catch(e){setError(e.message);}}
  async function downloadFile(attachment){try{const blob=await downloadAttachment(attachment.id,token);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=attachment.name;link.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}}
  if(!token||!user)return <Auth onSubmit={submitAuth} error={error} setForm={setForm} form={form} />;
  const nav=[['Overview',LayoutDashboard],['Projects',FolderKanban],['Tasks',ListTodo]];
  return <div className="app-shell"><aside className={`sidebar ${mobileNav?'show':''}`}><a className="brand" href="#home"><span className="brand-mark"><CheckCheck size={19}/></span><span>taskflow<span className="brand-dot">.</span></span></a><div className="workspace-label">WORKSPACE</div><div className="workspace"><div className="workspace-icon">W</div><span>Workspace</span><ChevronDown size={14}/></div><div className="side-section">MENU</div><nav>{nav.map(([name,Icon])=><button key={name} className={`nav-item ${tab===name?'active':''}`} onClick={()=>{setTab(name);setMobileNav(false);}}><Icon size={17}/><span>{name}</span>{name==='Tasks'&&<span className="nav-count">{dashboard?.stats?.pendingTasks||0}</span>}</button>)}</nav><div className="side-section projects-heading">YOUR PROJECTS <button title="Add project" onClick={()=>openForm('project')}><CirclePlus size={15}/></button></div><div className="project-nav">{projects.slice(0,5).map((p,i)=><button key={p.id} onClick={()=>{setTab('Projects');setSearch(p.name)}}><i className={`project-dot dot-${i%4}`}></i><span>{p.name}</span></button>)}</div><div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={17}/></div><b>Need a hand?</b><span>Check out our guide to get started.</span><button onClick={()=>notify('Guide coming soon')}>View guide <ArrowUpRight size={13}/></button></div><button className="profile" onClick={()=>{}}><span className="avatar">{initials(user.name)}</span><span className="profile-name"><b>{user.name}</b><small>{user.email}</small></span><MoreHorizontal size={18}/></button><button className="logout" onClick={async()=>{try{await request('/auth/logout',{method:'POST',token});}finally{signOut();}}}><LogOut size={15}/> Sign out</button></div></aside>
  <main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><div className="breadcrumbs"><span>Workspace</span><span className="crumb-slash">/</span><b>{tab}</b></div><div className="top-actions"><div className="top-search"><Search size={15}/><input placeholder="Search anything..." value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></div><button className="icon-button" onClick={()=>notify('You’re all caught up!')}><Bell size={17}/><i className="notification-dot"/></button><span className="top-divider"/><button className="avatar top-avatar" title={user.name}>{initials(user.name)}</button></div></header>
  <div className="page"><div className="page-heading"><div><div className="eyebrow"><Sparkles size={13}/> YOUR WORKSPACE</div><h1>{tab==='Overview'?`Good morning, ${user.name.split(' ')[0]}.`:`${tab}`}<span className="heading-period">.</span></h1><p>{tab==='Overview'?'Here’s what’s happening with your projects today.':tab==='Projects'?'Keep your work organized and moving forward.':'All your tasks, in one place.'}</p></div><div className="heading-actions"><button className="btn btn-light" onClick={load}><ArrowDownUp size={15}/> Refresh</button>{tab!=='Tasks'&&<button className="btn btn-primary" onClick={()=>openForm('project')}><CirclePlus size={16}/> New project</button>}{tab==='Tasks'&&<button className="btn btn-primary" onClick={()=>openForm('task')}><CirclePlus size={16}/> New task</button>}</div></div>
  {error&&<div className="alert"><span>{error}</span><button onClick={()=>setError('')}><X size={15}/></button></div>}
  {tab==='Overview'&&<><div className="stats-grid">{[['Total projects',dashboard?.stats.totalProjects||0,FolderKanban,'#edf0ff','+12% this month'],['Total tasks',dashboard?.stats.totalTasks||0,ClipboardList,'#e9f6ef','Across all projects'],['Completed tasks',dashboard?.stats.completedTasks||0,Check,'#f2edff',`${dashboard?.stats.totalTasks?Math.round(100*dashboard.stats.completedTasks/dashboard.stats.totalTasks):0}% completion rate`],['In progress',dashboard?.stats.projectsInProgress||0,Activity,'#fff3e4','Projects moving']].map(([name,value,Icon,color,meta],i)=><div className="stat-card" key={name}><div className="stat-top"><span>{name}</span><i style={{background:color}}><Icon size={16}/></i></div><div className="stat-value">{loading?'—':value}</div><div className="stat-meta">{i===0?<TrendingUp size={13} className="green-icon"/>:null}{meta}</div></div>)}</div><div className="overview-grid"><section className="panel project-panel"><div className="panel-heading"><div><h2>Recent projects</h2><p>A quick look at what you’re working on</p></div><button className="text-action" onClick={()=>setTab('Projects')}>View all <ArrowUpRight size={14}/></button></div><ProjectTable items={dashboard?.recentProjects||[]} open={openForm} remove={remove}/></section><section className="panel task-panel"><div className="panel-heading"><div><h2>Upcoming tasks</h2><p>What’s on your plate next</p></div><button className="icon-button subtle" onClick={()=>setTab('Tasks')}><ArrowUpRight size={16}/></button></div><TaskList items={dashboard?.upcomingTasks||[]} toggle={toggleTask} open={openForm} attach={attachFile} download={downloadFile}/></section></div><section className="panel all-task-panel"><div className="panel-heading"><div><h2>Recent tasks</h2><p>Track the small steps that move work forward</p></div><button className="text-action" onClick={()=>setTab('Tasks')}>All tasks <ArrowUpRight size={14}/></button></div><TaskList items={tasks.slice(0,5)} toggle={toggleTask} open={openForm} attach={attachFile} download={downloadFile}/></section></>}
  {tab==='Projects'&&<section className="panel list-panel"><div className="list-toolbar"><div><h2>All projects <span className="count-chip">{projects.length}</span></h2><p>Projects you own and manage</p></div><div className="filters"><select value={projectStatus} onChange={e=>setProjectStatus(e.target.value)}><option value="">All statuses</option><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></div></div><ProjectTable items={projects} open={openForm} remove={remove}/>{!projects.length&&<Empty icon={FolderKanban} title="No projects yet" text="Create a project to start organizing your work." action={()=>openForm('project')}/>}</section>}
  {tab==='Tasks'&&<section className="panel list-panel"><div className="list-toolbar"><div><h2>All tasks <span className="count-chip">{tasks.length}</span></h2><p>Stay on top of the details</p></div><div className="filters"><select value={taskStatus} onChange={e=>setTaskStatus(e.target.value)}><option value="">All statuses</option><option value="PENDING">Pending</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option><option value="LOW">Low priority</option><option value="MEDIUM">Medium priority</option><option value="HIGH">High priority</option></select></div></div><div className="task-list large-task-list">{tasks.map(task=><TaskRow key={task.id} item={task} toggle={toggleTask} open={openForm} remove={remove} attach={attachFile} download={downloadFile}/>)}</div>{!tasks.length&&<Empty icon={ListTodo} title="No tasks found" text="Add a task or adjust your filters." action={()=>openForm('task')}/>}</section>}
  <footer>© 2026 Taskflow <span>Made for focused work <Target size={13}/></span></footer></div></main>
  {mobileNav&&<button className="scrim" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}
  {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal('')}}><form className="modal" onSubmit={saveEntity}><div className="modal-head"><div><span className="eyebrow">{editing?'MAKE AN UPDATE':'ADD TO YOUR WORKSPACE'}</span><h2>{editing?'Edit':'New'} {modal}</h2></div><button type="button" className="icon-button" onClick={()=>setModal('')}><X size={18}/></button></div>{error&&<div className="alert">{error}</div>}<label>{modal} name<input required autoFocus maxLength="120" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder={modal==='project'?'e.g. Website redesign':'e.g. Draft project brief'}/></label><label>Description<textarea rows="3" maxLength="2000" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Add a few details..."/></label>{modal==='project'?<><label>Status<select value={form.status||'NOT_STARTED'} onChange={e=>setForm({...form,status:e.target.value})}><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></label><div className="form-row"><label>Start date<input type="date" value={form.startDate||''} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>End date<input type="date" value={form.endDate||''} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div></>:<><label>Project<select required value={form.projectId||''} onChange={e=>setForm({...form,projectId:e.target.value})}><option value="">Choose a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>Status<select value={form.status||'PENDING'} onChange={e=>setForm({...form,status:e.target.value})}><option value="PENDING">Pending</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></label><label>Priority<select value={form.priority||'MEDIUM'} onChange={e=>setForm({...form,priority:e.target.value})}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label></div><label>Due date<input type="date" value={form.dueDate||''} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></>}<div className="modal-actions"><button type="button" className="btn btn-light" onClick={()=>setModal('')}>Cancel</button><button className="btn btn-primary">{editing?'Save changes':`Create ${modal}`}</button></div></form></div>}
  {toast&&<div className="toast"><Check size={15}/>{toast}</div>}</div>
}
function Auth({onSubmit,error,setForm,form}){return <main className="auth-page"><div className="auth-decoration decor-one"/><div className="auth-decoration decor-two"/><div className="auth-card"><a className="brand auth-brand"><span className="brand-mark"><CheckCheck size={19}/></span><span>taskflow<span className="brand-dot">.</span></span></a><div className="auth-eyebrow">A CALMER WAY TO WORK</div><h1>{form.mode==='register'?'Create your account':'Welcome back.'}</h1><p className="auth-subtitle">{form.mode==='register'?'Bring your projects and tasks together.':'Pick up where you left off.'}</p>{error&&<div className="alert">{error}</div>}<form onSubmit={onSubmit} className="auth-form">{form.mode==='register'&&<label>Full name<input required minLength="2" autoComplete="name" placeholder="Alex Morgan" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email address<input required type="email" autoComplete="email" placeholder="you@example.com" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required type="password" minLength={form.mode==='register'?8:1} autoComplete={form.mode==='register'?'new-password':'current-password'} placeholder="At least 8 characters" value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="btn btn-primary auth-submit">{form.mode==='register'?'Create account':'Sign in'} <ArrowUpRight size={16}/></button></form><div className="auth-toggle">{form.mode==='register'?'Already have an account?':'New to Taskflow?'} <button onClick={()=>setForm({...form,mode:form.mode==='register'?'login':'register'})}>{form.mode==='register'?'Sign in':'Create an account'}</button></div><div className="auth-safe"><Check size={14}/> Your data is private and secure</div></div><div className="auth-caption">PLAN WITH CLARITY. <span>MOVE WITH CONFIDENCE.</span></div></main>}
function ProjectTable({items,open,remove}){return <div className="table-wrap"><table><thead><tr><th>PROJECT</th><th>STATUS</th><th>TASKS</th><th>LAST UPDATED</th><th></th></tr></thead><tbody>{items.map((p,i)=><tr key={p.id}><td><div className="project-cell"><div className={`project-icon project-icon-${i%4}`}><FolderKanban size={16}/></div><span><b>{p.name}</b><small>{p.description||'No description'}</small></span></div></td><td><Status value={p.status}/></td><td><span className="task-count"><ListTodo size={14}/>{p._count?.tasks??p.tasks?.length??0}</span></td><td className="muted-cell">{prettyDate(p.updatedAt||p.createdAt)}</td><td><RowActions onEdit={()=>open('project',p)} onDelete={()=>remove(p,'projects')}/></td></tr>)}</tbody></table></div>}
function TaskList({items,toggle,open,attach,download}){return <div className="task-list">{items.length?items.map(t=><TaskRow key={t.id} item={t} toggle={toggle} open={open} attach={attach} download={download}/>):<div className="mini-empty">Nothing on the list yet</div>}</div>}
function TaskRow({item,toggle,open,remove,attach,download}){return <div className="task-row"><button className={`task-check ${item.status==='COMPLETED'?'checked':''}`} onClick={()=>toggle(item)} aria-label="Toggle task complete">{item.status==='COMPLETED'&&<Check size={13}/>}</button><div className="task-copy"><b className={item.status==='COMPLETED'?'struck':''}>{item.name}</b><span>{item.project?.name||'Project'} <i/> <CalendarDays size={12}/>{prettyDate(item.dueDate)}</span>{(item.attachments?.length||attach)&&<div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap',marginTop:4}}>{item.attachments?.map(file=><button type="button" key={file.id} onClick={()=>download(file)} style={{border:0,padding:0,background:'none',color:'#467f5f',fontSize:11}}>{file.name} ({Math.ceil(file.size/1024)} KB)</button>)}{attach&&<label style={{color:'#467f5f',fontSize:11,cursor:'pointer'}}>+ Attach file<input type="file" style={{display:'none'}} onChange={e=>{if(e.target.files?.[0])attach(item.id,e.target.files[0]);e.target.value='';}}/></label>}</div>}</div><span className={`priority priority-${item.priority?.toLowerCase()}`}>{item.priority?.toLowerCase()}</span><Status value={item.status}/><RowActions onEdit={()=>open('task',item)} onDelete={remove?()=>remove(item,'tasks'):undefined}/></div>}
function Status({value}){const done=value==='COMPLETED';return <span className={`status status-${value?.toLowerCase()}`}><i/>{labels[value]||value}</span>}
function RowActions({onEdit,onDelete}){return <div className="row-actions"><button title="Edit" onClick={onEdit}><Settings2 size={14}/></button>{onDelete&&<button title="Delete" onClick={onDelete}><Trash2 size={14}/></button>}</div>}
function Empty({icon:Icon,title,text,action}){return <div className="empty-state"><div><Icon size={22}/></div><b>{title}</b><p>{text}</p><button className="btn btn-light" onClick={action}><CirclePlus size={15}/> Get started</button></div>}
export default App;
